#!/bin/bash

#SBATCH --mem=256000
#SBATCH --nodes=8
#SBATCH --ntasks=400
#SBATCH --cpus-per-task=1
#SBATCH --time=48:00:00
#SBATCH --account=desi
#SBATCH --qos=regular
#SBATCH --constraint=cpu
#SBATCH --licenses=cfs,SCRATCH
#SBATCH --image=zhouconghao/legacyhalos:latest
#SBATCH --output=/global/cfs/projectdirs/desi/users/zhouc/decals_lsb_production/scripts/slurm/log4/logslegacyhalos_array_test-%A-%a.txt
#SBATCH --mail-user=czhou64@ucsc.edu
#SBATCH --mail-type=ALL
#SBATCH --module=mpich

# sbatch legacyhsc-mpi.slurm
source /global/cfs/projectdirs/desi/users/zhouc/decals_lsb_production/scripts/envs/legacybgs-env_4
# coadds
time srun -N 8 -n 400 -c 1 shifter /global/cfs/projectdirs/desi/users/zhouc/desi_lsb/decals_lsb/forked_repos/legacyhalos/bin/legacybgs/legacybgs-mpi.sh coadds 1
# time srun -N 8 -n 400 -c 1 shifter /global/cfs/projectdirs/desi/users/zhouc/desi_lsb/decals_lsb/forked_repos/legacyhalos/bin/legacybgs/legacybgs-mpi.sh ellipse 1

# test
#time srun -N 2 -n 64 -c 1 shifter $LEGACYHALOS_CODE_DIR/bin/legacyhsc/legacyhsc-mpi.sh test 1
